sudo: required
services:
  - docker
  
before_install:

  - docker build -t testimage -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true testimage npm test -- --coverage
  
  
after_success:
  - docker build -t kumar/multi-client ./client
  - docker build -t kumar/multi-nginx ./nginx
  - docker build -t kumar/multi-server ./server
  - docker build -t kumar/multi-worker ./worker

#logging into docker cli from travis to dockerhub , we add the s and pwd in travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push sujith1788/multi-client
  - docker push sujith1788/multi-nginx
  - docker push sujith1788/multi-server
  - docker push sujith1788/multi-worker
#password copy chesi | tarvata daniki isthundi. idantah endukante travis adagaledu docker di username and pwd so maname istunnam.

#take images and push to dockerhub
 

  